bundler_args: --retry 3
language: objective-c
before_install:
 - export TZ=America/Chicago
 - npm install -g grunt-cli
install: npm install
before_script:
 - grunt shell:startDemo
 - travis_retry grunt test
 - grunt shell:stopDemo
 - grunt shell:startOSPi
 - travis_retry grunt test
 - grunt shell:stopOSPi
after_success:
 - ./node_modules/.bin/lcov-result-merger './coverage/results-*.lcov' './coverage/results.lcov'
 - cat coverage/results.lcov | ./node_modules/codecov.io/bin/codecov.io.js
 - cat coverage/results.lcov | ./node_modules/.bin/coveralls
notifications:
  on_failure: change
